// Pixel icon system — hand-drawn 8x8 grids on canvas, same ink-outline
// style as pet-art.ts, no image assets. Replaces every emoji in the UI
// (coins, item icons, sticker icons) so the whole plugin stays pixel-art.

import { useEffect, useRef, type FC } from 'react'

/** Single-char palette (o outline + fills shared with pet sprites). */
export const ICON_PAL: Record<string, string> = {
  o: '#4a4553', w: '#ffffff', e: '#3c3744',
  y: '#ffd33d', Y: '#d9a92a', t: '#e8434e', T: '#b32832',
  k: '#9c6640', K: '#7d4e2c', g: '#8fd0ff', z: '#8fa3c8',
  l: '#39496b', f: '#f4a45c', F: '#d9803a', p: '#f2839b',
  u: '#4d6efa', c: '#e7edff', s: '#ffe9dc', G: '#6bcb77',
}

/** All icon grids, 8 rows of exactly 8 chars ('.' = transparent). */
export const ICONS: Readonly<Record<string, readonly string[]>> = {
  // ── economy ──
  coin: [
    '..oooo..',
    '.oyyyyo.',
    'oyywyyyo',
    'oywyyyyo',
    'oyyyyyyo',
    'oyyyYYyo',
    '.oyYYyo.',
    '..oooo..',
  ],
  // ── shop items (Hitchhiker's catalog) ──
  fish: [
    '......o.',
    '.oooo.oo',
    'ogeGggoz',
    'ogegGgzz',
    'ogGegGzz',
    'ogGgGgzz',
    '.oooo.oo',
    '......o.',
  ],
  pill: [
    '..oooo..',
    '.owwwwo.',
    '.owwwwo.',
    '.otttto.',
    '.otttto.',
    '.otttto.',
    '..oooo..',
    '........',
  ],
  robot: [
    '...oo...',
    '.oooooo.',
    '.oweweo.',
    '.owwwwo.',
    'oowwwwoo',
    '.owwwwo.',
    '..o..o..',
    '........',
  ],
  cloud: [
    '........',
    '..oooo..',
    '.owwwwo.',
    'owwwwwwo',
    'owwwwwwo',
    'owwwwwwo',
    '.oooooo.',
    '........',
  ],
  fries: [
    '.o.oo.o.',
    '.oyoyoyo',
    '.oyoyoyo',
    '.otttto.',
    'otwwwwto',
    '.otttto.',
    '..oooo..',
    '........',
  ],
  scarf: [
    '........',
    '.oooooo.',
    'oppppppo',
    'oppppppo',
    '.oooooo.',
    '.oppo...',
    '.oppo...',
    '..oo....',
  ],
  potion: [
    '.oooooo.',
    '.occcco.',
    '.occcco.',
    'ooccccoo',
    'octttco.',
    '.otttto.',
    '..oooo..',
    '........',
  ],
  tea: [
    '........',
    '.w..w...',
    '..w..w..',
    '.oooooo.',
    '.oGGGGoo',
    '.oGGGGoo',
    '.oooooo.',
    '........',
  ],
  coffee: [
    '........',
    '.w..w...',
    '..w..w..',
    '.oooooo.',
    '.okkkkoo',
    '.okkkkoo',
    '.oooooo.',
    '........',
  ],
  leaf: [
    '.....oo.',
    '....oGo.',
    '...oGGo.',
    '..oGGGo.',
    '.oGGGo..',
    '.oGGo...',
    'oko.....',
    'o.......',
  ],
  sandwich: [
    '........',
    '...oo...',
    '..owso..',
    '.owstwo.',
    '.owttwo.',
    'owwwwwwo',
    '.oooooo.',
    '........',
  ],
  spray: [
    '..z.....',
    '.ooz....',
    '.oooo...',
    '.occco..',
    '.ozzzo..',
    '.ozzzo..',
    '.oooo...',
    '........',
  ],
  galaxy: [
    'oooooooo',
    'olwlowlo',
    'olllwllo',
    'olewlllo',
    'ollllwlo',
    'owlllleo',
    'ollllllo',
    'oooooooo',
  ],
  book: [
    '........',
    '.oooooo.',
    'owwoowwo',
    'ozwoozwo',
    'owwoowwo',
    'ozwoozwo',
    '.oooooo.',
    '........',
  ],
  donut: [
    '..oooo..',
    '.oppppo.',
    'oppwpppo',
    'opo..opo',
    'opo..opo',
    '.okkkko.',
    '..oooo..',
    '........',
  ],
  syringe: [
    '..oooo..',
    '.occcco.',
    '.octtco.',
    '.octtco.',
    '.occcco.',
    '..oooo..',
    '...oo...',
    '...o....',
  ],
  bolt: [
    '...ooo..',
    '..oyyo..',
    '.oyyoo..',
    '.oyyo...',
    'oyyoo...',
    '.oyo....',
    '.o......',
    '........',
  ],
  answer42: [
    '........',
    '........',
    'y.y.yyy.',
    'yy..y...',
    'y.y.yy..',
    'yyy.y...',
    '..y.yyy.',
    '........',
  ],
  planet: [
    '..oooo..',
    '.oyyyyo.',
    'oyywyyyo',
    'zzzyyyzz',
    'oyyyYYyo',
    '.oyYYyo.',
    '..oooo..',
    '........',
  ],
  ticket: [
    '..ooooo.',
    '.owwwwyo',
    '.owwwwyo',
    'o.wwwwyo',
    '.owwwwyo',
    '.owwwwyo',
    '..ooooo.',
    '........',
  ],
  letter: [
    '........',
    '.oooooo.',
    'ozwwwwzo',
    'ozowwozo',
    'ozoowozo',
    'ozzzzzzo',
    '.oooooo.',
    '........',
  ],
  // ── special / achievement items ──
  trophy: [
    '.oooooo.',
    'oyyyyyyo',
    'oyyyyyyo',
    '.oyyyyo.',
    '..oyyo..',
    '...oo...',
    '.oooooo.',
    '........',
  ],
  medal: [
    '........',
    '.o.oo.o.',
    '..otto..',
    '..oooo..',
    '.oyyyyo.',
    'oyywyyyo',
    '.oyyyyo.',
    '..oooo..',
  ],
  sparkle: [
    '...o....',
    '..oyo...',
    '.oyyyo..',
    'oyywyyo.',
    '.oyyyo..',
    '..oyo...',
    '...o....',
    '........',
  ],
  // ── stickers ──
  star: [
    '...oo...',
    '..oyyo..',
    'oyyyyyyo',
    '.oyyyyo.',
    '..oyyo..',
    '.oy.oyo.',
    '.o...o..',
    '........',
  ],
  heart: [
    '.oooooo.',
    'oyyoyyyo',
    'oyyyyyyo',
    'oyyyyyyo',
    '.oyyyyo.',
    '..oyyo..',
    '...oo...',
    '........',
  ],
  bug: [
    '..o..o..',
    '.oooooo.',
    'oGeGGGo.',
    'oGGGGGo.',
    '.oooooo.',
    '.o.o.o..',
    '........',
    '........',
  ],
  rocket: [
    '...oo...',
    '..offo..',
    '..owwo..',
    '.owwwwo.',
    '.owwwwo.',
    '.oooooo.',
    '.f.ff.f.',
    '..f..f..',
  ],
  palette: [
    '.oooooo.',
    'owoytogo',
    'oooooooo',
    'oo.ooooo',
    'oo.ooooo',
    'oooooooo',
    '.oooooo.',
    '........',
  ],
  fire: [
    '...o....',
    '..ofo...',
    '.offfo..',
    '.offfo..',
    'offfffo.',
    'ofyyyfo.',
    '.ofyfo..',
    '..ooo...',
  ],
  crown: [
    'o.ooo.o.',
    'oooooooo',
    'oyyyyyyo',
    'oyytyyo.',
    'oyyyyyyo',
    'oooooooo',
    '........',
    '........',
  ],
  clip: [
    '..ooooo.',
    '.ozeezo.',
    '.ozeozo.',
    '.ozeo.o.',
    '.ozeoo..',
    '.ozeezo.',
    '..ozzoo.',
    '..oooo..',
  ],
  compass: [
    '..oooo..',
    '.ozzzzo.',
    'ozwttzzo',
    'oztttzzo',
    '.ozzzzo.',
    '..oooo..',
    '........',
    '........',
  ],
  map: [
    'oooooooo',
    'owwwwwwo',
    'otwwwwwo',
    'owtwwwwo',
    'owwtwwwo',
    'owwwtwwo',
    'owwwwwto',
    'oooooooo',
  ],
  gem: [
    '.oooooo.',
    'ogwggzzo',
    'ogggggzo',
    '.ogggzo.',
    '.oggzo..',
    '..ogzo..',
    '...oo...',
    '........',
  ],
  sun: [
    'o..oo..o',
    '.oyyyyo.',
    'ooywyyoo',
    'oyywyyyo',
    'oyywyyyo',
    'ooyyyyo.',
    '.oyyyyo.',
    'o..oo..o',
  ],
  moon: [
    '..oooo..',
    '.oyyyyo.',
    '.oyyoo..',
    '.oyyo...',
    '.oyyoo..',
    '.oyyyyo.',
    '..oooo..',
    '........',
  ],
  handshake: [
    'oo....oo',
    'oso..oso',
    '.osssso.',
    '..osso..',
    '..osso..',
    '.osssso.',
    'oso..oso',
    'oo....oo',
  ],
  megaphone: [
    '........',
    '.k......',
    '.okooo..',
    '.okttto.',
    '.okttto.',
    '.okooo..',
    '.k......',
    '........',
  ],
  rainbow: [
    '........',
    '..tttt..',
    '.tyyyyt.',
    'tyGGGGyt',
    'tyG..Gyt',
    'to....ot',
    '........',
    '........',
  ],
  aurora: [
    '..G.p.u.',
    '.Gy.p.u.',
    'Gyy.ppu.',
    'Gyyppuu.',
    '.yy.pu..',
    '.yy.p.u.',
    '..y...u.',
    '........',
  ],
  dice: [
    'oooooooo',
    'owwwwwwo',
    'owewwewo',
    'owwwewwo',
    'owewwewo',
    'owwwwwwo',
    'oooooooo',
    '........',
  ],
  joystick: [
    '...oo...',
    '...oo...',
    '.oooooo.',
    'ozewwezo',
    'ozzzzzzo',
    '.oooooo.',
    '........',
    '........',
  ],
  key: [
    '..ooo...',
    '.oyyyo..',
    'oyywyyyo',
    'oyyyyyyo',
    '..oo..o.',
    '..oooo..',
    '........',
    '........',
  ],
  lantern: [
    '...oo...',
    '..okko..',
    '.oooooo.',
    '.otwwto.',
    'otwwwwto',
    '.otttto.',
    '..oooo..',
    '...oo...',
  ],
}

/** Draw one icon grid onto a square canvas (scales to canvas size). */
export function drawIcon(cv: HTMLCanvasElement, grid: readonly string[]): void {
  const sc = cv.width / 8
  const x = cv.getContext('2d')
  if (!x) return
  x.clearRect(0, 0, cv.width, cv.height)
  for (let y = 0; y < 8; y++) {
    const row = grid[y] ?? ''
    for (let i = 0; i < 8; i++) {
      const ch = row[i]
      if (ch === undefined || ch === '.') continue
      x.fillStyle = ICON_PAL[ch] ?? '#f0f'
      x.fillRect(i * sc, y * sc, sc, sc)
    }
  }
}

/** Inline pixel icon: native 24px canvas (3x supersample), CSS-sized. */
export const PixelIcon: FC<{ icon: string; size?: number }> = ({ icon, size = 14 }) => {
  const ref = useRef<HTMLCanvasElement>(null)
  const grid = ICONS[icon] ?? ICONS.coin
  useEffect(() => {
    if (ref.current) drawIcon(ref.current, grid)
  }, [grid])
  return (
    <canvas
      ref={ref}
      width={24}
      height={24}
      style={{ width: size, height: size, imageRendering: 'pixelated', verticalAlign: '-2px', flex: 'none' }}
    />
  )
}
